// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB90p6D12vmhLTBZ6FJLLs5c7s72p5tcwk',
    appId: '1:31522847211:web:41485ac33e434f4ca481ae',
    messagingSenderId: '31522847211',
    projectId: 'daily-utility-1d724',
    authDomain: 'daily-utility-1d724.firebaseapp.com',
    storageBucket: 'daily-utility-1d724.firebasestorage.app',
    measurementId: 'G-ZMPEBQ0NYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMmtdgF_VMV1FYbeetlnmwwoRQgR78pY',
    appId: '1:31522847211:android:2d6f4992cab45064a481ae',
    messagingSenderId: '31522847211',
    projectId: 'daily-utility-1d724',
    storageBucket: 'daily-utility-1d724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7io1YZkeYSC28zvTSCfRdCin04wJCfGI',
    appId: '1:31522847211:ios:cebc8517757150aaa481ae',
    messagingSenderId: '31522847211',
    projectId: 'daily-utility-1d724',
    storageBucket: 'daily-utility-1d724.firebasestorage.app',
    iosBundleId: 'com.example.dailyutulity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7io1YZkeYSC28zvTSCfRdCin04wJCfGI',
    appId: '1:31522847211:ios:cebc8517757150aaa481ae',
    messagingSenderId: '31522847211',
    projectId: 'daily-utility-1d724',
    storageBucket: 'daily-utility-1d724.firebasestorage.app',
    iosBundleId: 'com.example.dailyutulity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB90p6D12vmhLTBZ6FJLLs5c7s72p5tcwk',
    appId: '1:31522847211:web:ab588c07385901dea481ae',
    messagingSenderId: '31522847211',
    projectId: 'daily-utility-1d724',
    authDomain: 'daily-utility-1d724.firebaseapp.com',
    storageBucket: 'daily-utility-1d724.firebasestorage.app',
    measurementId: 'G-5HCDEGHB75',
  );
}
