import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'firebase_options.dart';
import 'screens/splash/splash_screen.dart';
import 'services/hive_service.dart';
import 'services/locale_service.dart';
import 'services/notice_service.dart';
import 'services/notification_service.dart';
import 'services/settings_service.dart';
import 'theme/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Best-effort load of any .env keys (kept for future config use; the
  // Firebase project is wired through `firebase_options.dart`).
  try {
    await dotenv.load(fileName: '.env');
  } catch (_) {
    // .env is optional now; ignore if missing.
  }

  await HiveService.init();
  await SettingsService.init();
  await LocaleService.init();
  await NotificationService.init();

  // Initialise Firebase with the platform-specific options generated by
  // the FlutterFire CLI (lib/firebase_options.dart). If init throws we
  // still run the app — NoticeService will simply report unconfigured
  // and the bell icon will hide / show a friendly message.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // ignore: avoid_print
    // ignore: unused_local_variable
    final _ = e; // keep the catch narrow; surfaces only in logs.
  }

  await NoticeService.instance.init();

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
  ));

  runApp(const DailyUtilityApp());
}

class DailyUtilityApp extends StatefulWidget {
  const DailyUtilityApp({super.key});

  @override
  State<DailyUtilityApp> createState() => _DailyUtilityAppState();
}

class _DailyUtilityAppState extends State<DailyUtilityApp> {
  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<int>(
      valueListenable: SettingsService.instance.revision,
      builder: (context, _, __) {
        return ValueListenableBuilder<Locale>(
          valueListenable: LocaleService.instance.notifier,
          builder: (context, locale, _) {
            return MaterialApp(
              title: 'Daily Utility',
              debugShowCheckedModeBanner: false,
              theme: AppTheme.light(),
              darkTheme: AppTheme.dark(),
              themeMode: SettingsService.instance.themeMode,
              locale: locale,
              supportedLocales: const [Locale('en'), Locale('bn')],
              localizationsDelegates: const [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              home: const SplashScreen(),
            );
          },
        );
      },
    );
  }
}
