-- ============================================================================
-- Daily Utility — Firestore `notice` collection schema
-- ============================================================================
-- The app reads from the `notice` collection in the Firestore project
-- `daily-utility-1d724` (configured via firebase_options.dart).
--
-- Document fields (read by the Flutter client):
--
--   title      string   REQUIRED  -- the notice headline
--   para       string   REQUIRED  -- the notice body / description
--   imgurl     string   optional  -- image URL shown at the top of the card
--   linkurl    string   optional  -- "Read more" button URL (external link)
--   createdAt  timestamp optional -- used for sorting newest first
--   isPinned   bool     optional  -- when true, sorts above all others
--
-- Example: create a notice document in the Firestore console, e.g.
--   Collection: notice
--   Document ID: (auto)
--     title:      "Welcome"
--     para:       "Thanks for installing Daily Utility!"
--     imgurl:     "https://example.com/banner.png"
--     linkurl:    "https://example.com/welcome"
--     createdAt:  (server timestamp)
--     isPinned:   true
--
-- ============================================================================
-- Optional one-time seed via gcloud / firebase CLI:
-- ============================================================================
-- firebase firestore:set ./firestore-seed/notices.json --project daily-utility-1d724
--
-- firestore-seed/notices.json
-- [
--   {
--     "title": "Welcome",
--     "para":  "Thanks for installing Daily Utility!",
--     "imgurl": "",
--     "linkurl": "",
--     "createdAt": { "_seconds": 0 },
--     "isPinned": true
--   }
-- ]
-- ============================================================================
